### ISSUE TITLE
EventEmitter memory leak detected

### ISSUE THREAD

**Issue by keyurshah** [SnowdogApps/magento2-frontools#109]
encountering an error running gulp and wondering if you have encountered this before. 

seems to have happened after updating to the latest magento 2.1.2, but not sure if it's related to that. was working fine before that.

I get this when running `gulp dev`

```
(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:252:17)
    at Object.fs.watchFile (fs.js:1424:8)
    at Gaze._pollFile (/home/vagrant/sites_local/www.magento.dev/magento2/current/vendor/snowdog/frontools/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:329:10)
    at /home/vagrant/sites_local/www.magento.dev/magento2/current/vendor/snowdog/frontools/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:411:12
    at Array.forEach (native)
    at /home/vagrant/sites_local/www.magento.dev/magento2/current/vendor/snowdog/frontools/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:409:11
    at iterate (/home/vagrant/sites_local/www.magento.dev/magento2/current/vendor/snowdog/frontools/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /home/vagrant/sites_local/www.magento.dev/magento2/current/vendor/snowdog/frontools/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /home/vagrant/sites_local/www.magento.dev/magento2/current/vendor/snowdog/frontools/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/home/vagrant/sites_local/www.magento.dev/magento2/current/vendor/snowdog/frontools/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.

```

I am running this inside a vagrant machine (homestead)

**Comment by Igloczek** [comment]
What's your node.js version? 
Do you have many themes added or other unusual things that may help me to reproduce this issue?

**Comment by keyurshah** [comment]
I think I got it. I manually deleted /pub/static and I think that made it work. I had a bash script to run all the steps, and I forgot to add `gulp clean`

here's a bash script that I ported over from Alan Kent in case it's helpful for anyone

```
#!/bin/sh

set -x
rm -rf /magento/var/{cache,page_cache,session,view_preprocessed}
php bin/magento cache:disable config

# Redeploy to pick up new files, compile styles, watch for file changes.
cd tools
gulp clean
gulp deploy
gulp styles
gulp docs
gulp dev --theme <your_theme_name>
```

thank you for your hard work on this project. it's a lifesaver!

**Comment by Igloczek** [comment]
BTW. `deploy` and `styles` also use `--theme` param. I should add it to `clean` too, to save some time :)

**Comment by keyurshah** [comment]
thanks for the clarification. that makes the script a bit faster

updated:

```
#!/bin/sh

set -x

# Clear out some caches
rm -rf /magento/var/{cache,page_cache,session,view_preprocessed}

php bin/magento cache:disable config

# Redeploy to pick up new files, compile styles, watch for file changes.
cd tools
gulp clean
gulp deploy --theme <your_theme_name>
gulp styles --theme <your_theme_name>
gulp docs
gulp dev --theme <your_theme_name>
```
