### ISSUE TITLE
gulp couldn't open readme.md on Ubuntu because it's case sensitive 

### ISSUE THREAD

**Issue by talalus** [SnowdogApps/magento2-frontools#119]
couldn't run 'gulp' on Ubuntu (Ubuntu 14.04.5 LTS) :
```
[08:50:53] Error: ENOENT: no such file or directory, open './readme.md'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.module.exports (/var/www/stage-m2.homebyeve.com/releases/20161028083436/vendor/snowdog/frontools/task/default.js:12:41)
    at module.exports (/var/www/stage-m2.homebyeve.com/releases/20161028083436/vendor/snowdog/frontools/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/stage-m2.homebyeve.com/releases/20161028083436/vendor/snowdog/frontools/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/stage-m2.homebyeve.com/releases/20161028083436/vendor/snowdog/frontools/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/stage-m2.homebyeve.com/releases/20161028083436/vendor/snowdog/frontools/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
    at nextTickCallbackWith0Args (node.js:420:9)
```

**Comment by Igloczek** [comment]
Fixed in 1.1.1.
