### ISSUE TITLE
Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by flakerimi** [SnowdogApps/magento2-frontools#15]
Running `/home/magento/tools# gulp styles --theme uw`
```
[15:58:10] Using gulpfile /home/magento/tools/gulpfile.js
[15:58:10] Starting 'styles'...
[15:58:10] 'styles' errored after 1.94 ms
[15:58:10] TypeError: Cannot read property 'locale' of undefined
    at /home/magento/tools/tasks/styles.js:12:25
    at Array.forEach (native)
    at Object.module.exports.themes.forEach (/home/magento/tools/tasks/styles.js:11:10)
    at module.exports (/home/magento/tools/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/magento/tools/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/magento/tools/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/magento/tools/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by Igloczek** [comment]
Did you create proper configuration in `configs/themes.json`?
