### ISSUE TITLE
No Style in frontend after doing all this coding adventure

### ISSUE THREAD

**Issue by gcampedelli** [SnowdogApps/magento2-frontools#157]
I'm not a developer, but I arrived to this point and I have no style in frontend

<details>

```
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/config$ nano themes.json
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/config$ cd /var/www/magento2/app/design/frontend/snowdog/vendor/sn
owdog/frontools/
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools$ gulp styles --theme sass-blank
[19:27:16] Using gulpfile /var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/gulpfile.js
[19:27:16] Starting 'styles'...
[19:27:16] Starting 'inheritance'...
[19:27:16] Finished 'inheritance' after 7.43 ms
[19:27:17] 'styles' errored after 605 ms
[19:27:17] Error: ENOENT: no such file or directory, scandir '/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools$ cd config
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/config$ nano themes.json
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/config$ cd /var/www/magento2/app/design/frontend/snowdog/vendor/sn
owdog/frontools/
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools$ gulp styles --theme sass-blank
[19:29:32] Using gulpfile /var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/gulpfile.js
[19:29:32] Starting 'styles'...
[19:29:32] Starting 'inheritance'...
[19:29:32] Finished 'inheritance' after 6.68 ms
[19:29:32] 'styles' errored after 285 ms
[19:29:32] Error: ENOENT: no such file or directory, scandir '/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools$ sudo gulp styles --theme sass-blank
[19:29:37] Using gulpfile /var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/gulpfile.js
[19:29:37] Starting 'styles'...
[19:29:37] Starting 'inheritance'...
[19:29:37] Finished 'inheritance' after 7.88 ms
[19:29:38] 'styles' errored after 283 ms
[19:29:38] Error: ENOENT: no such file or directory, scandir '/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools$ ls
composer.json  gulpfile.js  LICENSE       package.json  task      themes.json
config         helper       node_modules  README.md     __test__  yarn.lock
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools$ cd node_modules
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules$ ls
abbrev                        json-stringify-safe
accepts                       jsprim
acorn                         js-tokens
acorn-jsx                     js-yaml
acorn-object-spread           kind-of
after                         klaw
ajv                           known-css-properties
ajv-keywords                  lazy-cache
align-text                    lazy-debug-legacy
alphanum-sort                 lcid
amdefine                      ldjson-stream
ansicolors                    levn
ansi-escapes                  liftoff
ansi-regex                    limiter
ansi-styles                   load-json-file
anymatch                      localtunnel
aproba                        lodash
archy                         lodash._arraycopy
are-we-there-yet              lodash._arrayeach
argparse                      lodash.assign
arraybuffer.slice             lodash.assignwith
array-differ                  lodash._baseassign
array-find-index              lodash._baseclone
array-union                   lodash._basecopy
array-uniq                    lodash._basefor
array-unique                  lodash._basetostring
arr-diff                      lodash._basevalues
arr-flatten                   lodash._bindcallback
arrify                        lodash.capitalize
asn1                          lodash.clonedeep
assert-plus                   lodash.escape
async                         lodash._getnative
async-each                    lodash.indexof
async-each-series             lodash.isarguments
async-foreach                 lodash.isarray
asynckit                      lodash.isempty
atob                          lodash.isfinite
autoprefixer                  lodash._isiterateecall
aws4                          lodash.isplainobject
aws-sign2                     lodash.isstring
babel-code-frame              lodash.kebabcase
backo2                        lodash.keys
balanced-match                lodash.mapvalues
base64-arraybuffer            lodash.memoize
base64id                      lodash.pick
batch                         lodash._reescape
bcrypt-pbkdf                  lodash._reevaluate
beeper                        lodash._reinterpolate
better-assert                 lodash.restparam
binary-extensions             lodash._root
blob                          lodash.template
block-stream                  lodash.templatesettings
boom                          lodash.uniq
brace-expansion               log-symbols
braces                        longest
browserslist                  loud-rejection
browser-sync                  lru-cache
browser-sync-client           macaddress
browser-sync-ui               magic-string
bs-recipes                    make-error
buble                         make-error-cause
bubleify                      map-cache
buffer-shims                  map-obj
bufferstreams                 marked
builtin-modules               marked-terminal
caller-path                   math-expression-evaluator
callsite                      meow
callsites                     merge
camelcase                     merge-stream
camelcase-keys                micromatch
caniuse-api                   mime
caniuse-db                    mime-db
cardinal                      mime-types
caseless                      minimatch
center-align                  minimist
chalk                         mkdirp
chokidar                      ms
circular-json                 multimatch
clap                          multipipe
cli-cursor                    mute-stream
cli-table                     nan
cliui                         natives
cli-usage                     natural-compare
cli-width                     negotiator
clone                         node-emoji
cloneable-readable            node.extend
clone-buffer                  node-gyp
clone-regexp                  node-notifier
clone-stats                   node-sass
co                            nopt
coa                           normalize-package-data
code-point-at                 normalize-path
color                         normalize-range
color-convert                 normalize-selector
color-diff                    normalize-url
colorguard                    npmlog
colormin                      num2fraction
color-name                    number-is-nan
colors                        oauth-sign
color-string                  object-assign
combined-stream               object-component
commander                     object.omit
component-bind                object-path
component-emitter             once
component-inherit             onecolor
concat-map                    onetime
concat-stream                 on-finished
concat-with-sourcemaps        openurl
connect                       opn
connect-history-api-fallback  optionator
console-control-strings       options
convert-source-map            orchestrator
cookie                        ordered-read-streams
core-util-is                  osenv
cosmiconfig                   os-homedir
cross-spawn                   os-locale
cryptiles                     os-tmpdir
css                           parse-filepath
css-color-names               parse-glob
cssnano                       parsejson
csso                          parse-json
css-rule-stream               parse-passwd
css-tokenize                  parseqs
currently-unhandled           parseuri
d                             parseurl
dashdash                      path-exists
dateformat                    path-is-absolute
debug                         path-is-inside
debug-fabulous                path-root
decamelize                    path-root-regex
deep-is                       path-type
defaults                      pify
defined                       pinkie
del                           pinkie-promise
delayed-stream                pipetteur
delegates                     plur
depd                          pluralize
deprecated                    portscanner
destroy                       postcss
detect-file                   postcss-calc
detect-newline                postcss-colormin
dev-ip                        postcss-convert-values
doctrine                      postcss-discard-comments
doiuse                        postcss-discard-duplicates
duplexer                      postcss-discard-empty
duplexer2                     postcss-discard-overridden
duplexify                     postcss-discard-unused
easy-extender                 postcss-filter-plugins
eazy-logger                   postcss-less
ecc-jsbn                      postcss-media-query-parser
ee-first                      postcss-merge-idents
electron-to-chromium          postcss-merge-longhand
emitter-steward               postcss-merge-rules
encodeurl                     postcss-message-helpers
end-of-stream                 postcss-minify-font-values
engine.io                     postcss-minify-gradients
engine.io-client              postcss-minify-params
engine.io-parser              postcss-minify-selectors
error-ex                      postcss-normalize-charset
es5-ext                       postcss-normalize-url
es6-iterator                  postcss-ordered-values
es6-map                       postcss-reduce-idents
es6-set                       postcss-reduce-initial
es6-symbol                    postcss-reduce-transforms
es6-weak-map                  postcss-reporter
escape-html                   postcss-resolve-nested-selector
escape-string-regexp          postcss-scss
escope                        postcss-selector-parser
eslint                        postcss-svgo
espree                        postcss-unique-selectors
esprima                       postcss-value-parser
esrecurse                     postcss-zindex
estraverse                    prelude-ls
esutils                       prepend-http
etag                          preserve
event-emitter                 pretty-hrtime
eventemitter3                 process-nextick-args
execall                       progress
exit-hook                     pseudomap
expand-brackets               punycode
expand-range                  q
expand-tilde                  qs
express                       query-string
extend                        randomatic
extglob                       range-parser
extsprintf                    readable-stream
fancy-log                     readdirp
fast-levenshtein              read-file-stdin
figures                       readline2
file-entry-cache              read-pkg
filename-regex                read-pkg-up
fill-range                    rechoir
finalhandler                  redent
find-index                    redeyed
find-up                       reduce-css-calc
findup-sync                   reduce-function-call
fined                         regex-cache
first-chunk-stream            remove-trailing-separator
flagged-respawn               rename
flat-cache                    repeat-element
flatten                       repeating
forever-agent                 repeat-string
for-in                        replace-ext
fork-stream                   request
form-data                     require-directory
formidable                    require-from-string
for-own                       require-main-filename
fresh                         requires-port
front-matter                  require-uncached
frontools                     resolve
fs-exists-sync                resolve-dir
fs-extra                      resolve-from
fs.realpath                   resolve-url
fstream                       resp-modifier
function-bind                 restore-cursor
gather-stream                 right-align
gauge                         rimraf
gaze                          run-async
generate-function             run-sequence
generate-object-property      rx
get-caller-file               rx-lite
getpass                       sass-graph
get-stdin                     sass-lint
glob                          sax
glob2base                     semver
global-modules                send
global-prefix                 sequencify
globals                       serve-index
glob-base                     server-destroy
globby                        serve-static
globjoin                      set-blocking
glob-parent                   set-immediate-shim
glob-stream                   setprototypeof
globule                       shelljs
glob-watcher                  shellwords
glogg                         sigmund
gonzales-pe                   signal-exit
graceful-fs                   slice-ansi
graceful-readlink             sntp
growly                        socket.io
gulp                          socket.io-adapter
gulp-concat                   socket.io-client
gulp-eslint                   socket.io-parser
gulp-if                       sort-keys
gulp-load-plugins             source-map
gulplog                       source-map-resolve
gulp-logger                   source-map-url
gulp-match                    sparkles
gulp-multi-dest               spdx-correct
gulp-notify                   spdx-expression-parse
gulp-plumber                  spdx-license-ids
gulp-postcss                  specificity
gulp-rimraf                   split2
gulp-sass                     sprintf-js
gulp-sass-lint                sshpk
gulp-sourcemaps               statuses
gulp-task-loader              stream-combiner
gulp-uglify                   stream-consume
gulp-util                     stream-shift
har-validator                 stream-throttle
has                           strict-uri-encode
has-ansi                      string_decoder
has-binary                    string.prototype.codepointat
has-cors                      stringstream
has-flag                      string-width
has-gulplog                   strip-ansi
has-unicode                   strip-bom
hawk                          strip-indent
hoek                          strip-json-comments
homedir-polyfill              stylehacks
hosted-git-info               stylelint
html-comment-regex            style-search
html-tags                     sugarss
http-errors                   supports-color
http-proxy                    svgo
http-signature                svg-tags
ignore                        synesthesia
immutable                     table
imurmurhash                   tar
indent-string                 ternary-stream
indexes-of                    text-table
indexof                       tfunk
inflight                      through
inherits                      through2
ini                           tildify
in-publish                    time-stamp
inquirer                      to-array
interpret                     tough-cookie
invert-kv                     trim-newlines
irregular-plurals             tryit
is                            tunnel-agent
is-absolute                   tweetnacl
is-absolute-url               type-check
isarray                       typedarray
is-arrayish                   ua-parser-js
is-binary-path                uglify-js
is-buffer                     uglify-save-license
is-builtin-module             uglify-to-browserify
is-dotfile                    ultron
is-equal-shallow              unc-path-regex
isexe                         underscore
is-extendable                 uniq
is-extglob                    uniqid
is-finite                     uniqs
is-fullwidth-code-point       unique-stream
is-glob                       unpipe
is-my-json-valid              urix
is-number                     user-home
is-number-like                util
isobject                      util-deprecate
is-path-cwd                   utils-merge
is-path-in-cwd                uuid
is-path-inside                v8flags
is-plain-obj                  validate-npm-package-license
is-posix-bracket              vendors
is-primitive                  verror
is-property                   vinyl
is-regexp                     vinyl-fs
is-relative                   vinyl-sourcemaps-apply
is-resolvable                 vlq
isstream                      weinre
is-stream                     whet.extend
is-supported-regexp-flag      which
is-svg                        which-module
is-typedarray                 wide-align
is-unc-path                   window-size
is-utf8                       wordwrap
is-windows                    wrap-ansi
jodid25519                    wrappy
js-base64                     write
jsbn                          write-file-stdout
json3                         ws
jsonfile                      wtf-8
jsonfilter                    xmlhttprequest-ssl
jsonify                       xtend
jsonparse                     y18n
jsonpointer                   yallist
json-schema                   yargs
json-stable-stringify         yargs-parser
JSONStream                    yeast
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules$ cd node_sass
-bash: cd: node_sass: No such file or directory
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules$ cd node-sass
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass$ ls
bin          CHANGELOG.md  LICENSE       package.json  scripts  test
binding.gyp  lib           node_modules  README.md     src
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass$ mkdir vendor
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass$ cd /var/www/magento2/app/design/frontend/s
nowdog/vendor/snowdog/frontools/
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools$ gulp styles --theme sass-blank
[19:33:52] Using gulpfile /var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/gulpfile.js
[19:33:52] Starting 'styles'...
[19:33:52] Starting 'inheritance'...
[19:33:52] Finished 'inheritance' after 6.48 ms
[19:33:52] 'styles' errored after 277 ms
[19:33:52] Error: Missing binding /var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/vendor/linux-x64-46/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 4.x

Found bindings for the following environments:


This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at module.exports (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:410:26)
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools$ npm rebuild node-sass

> node-sass@3.13.1 install /var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-46_binding.node
Download complete  ] - :
Binary saved to /var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/vendor/linux-x64-46/binding.node
Caching binary to /home/ubuntu/.npm/node-sass/3.13.1/linux-x64-46_binding.node

> node-sass@3.13.1 postinstall /var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass
> node scripts/build.js

Binary found at /var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass/vendor/linux-x64-46/binding.node
Testing binary
Binary is fine
node-sass@3.13.1 /var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/node_modules/node-sass
ubuntu@ip-xxx-xxx--208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools$ gulp styles --theme sass-blank
[19:34:45] Using gulpfile /var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools/gulpfile.js
[19:34:45] Starting 'styles'...
[19:34:45] Starting 'inheritance'...
[19:34:45] Finished 'inheritance' after 7.09 ms
[19:34:46] Finished 'styles' after 1.43 s
ubuntu@ip-xxx.xxx-208:/var/www/magento2/app/design/frontend/snowdog/vendor/snowdog/frontools$ 
```

</details>

Is there anything I'm missing? I was expecting a similar page to default Magento Blank Theme. Can you help me on that?

**Comment by Igloczek** [comment]
Ouh... Few questions:
1. How did you installed Magento2?
2. How and where did you installed `sass-blank-theme`?
3. Why do you want to use this tools and theme, if you are not a developer?

Advices:
1. Proper path for Frontools is in your case`/var/www/magento2/vendor/snowdog/frontools`, that's why Frontools can't handle processing of your styles.
2. Never modify anything inside `node_modules` directory. If you have any troubles, just remove this directory and run `npm install` again. If problem will still exist, check system requirements i.e. node.js version (you need versions`>=6.9.1`)

**Comment by gcampedelli** [comment]
Thank you for your answer Igloczek. It is always time to learn with our mistakes. 

Questions 1 and 2 :Fresh Magento install on Ubuntu 16.04 at /var/www/html (I’ve corrected this by reinstalling Magento) (Answer for question 3 at end)

I installed MySql, Apache2, all requirements and went to magento setup page and installed. Then I did as follow

Install Node.js - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash

$nvm install 6.9.1 
$nvm use 6.9.1 
$nvm alias default 6.9.1
$npm install -g gulp-cli

Switched to my Magento2 dir

cd /var/www/html/Magento2

composer require snowdog/theme-blank-sass

Got an error

“Problem 1
    - Installation request for snowdog/theme-blank-sass ^0.9.2 -> satisfiable by snowdog/theme-blank-sass[0.9.2].
    - snowdog/theme-blank-sass 0.9.2 requires magento/framework 100.1.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.”

Proceed to Manual Install

Downloaded Theme from Github repository v.0.9.0

Upload to /app/design/frontend/snowdog/theme-blank-sass

unzip 

Changed dir again to /magento2/vendor/snowdog/frontools
npm install error killed

Then manual install of tree in composer.json 

run command gulp setup

Removed .sample from Themes.json in config dir

run command gulp styles --theme blank

[01:47:21] Working directory changed to /var/www/html/magento2/vendor/snowdog/frontools
[01:47:21] Using gulpfile /var/www/html/magento2/vendor/snowdog/frontools/gulpfile.js
[01:47:21] Starting 'styles'...
[01:47:21] Starting 'inheritance'...
[01:47:21] Finished 'inheritance' after 9.16 ms
[01:47:22] Finished 'styles' after 810 ms

cd to bin and run php magento setup:static-content:deploy -f

Got error:

[UnexpectedValueException]                                                   
  Could not parse theme static file '/var/www/html/magento2/app/design/fronte  
  nd/snowdog/theme-blank-sass/__test__/web/css/styles.css'



Now I get 500 error in http

Any ideas??

Answer to question 3: Well, I'm a journalist and by this time, I'm a coffee producer. I mainly work with branding and I have some experience with Magento 1. I'm trying to learn all this thing of Magento 2 development to setup my coffee store with my look and feel as I have lots of experience as designer. So, I'm trying to become a developer. I make lots of mistakes, but I think they are an opportunity to learn. But why work with this tools? Well, I think it is a very good idea to have SASS on Magento and why should I waste your nice work on that? We all face problems during development, it is nice if we can share and make things better from there. If you can help with this issue I would be very happy. 

Thank you again for your answer, 
Gabriela

**Comment by Igloczek** [comment]
Looks like you are trying to use not stable version and this lead you to weird solutions.

Try to install M2.1.3 via composer, then add theme and frontools via composer too and it will just start working.

When you are using composer all of necessary code sits inside `vendor/{vendor_name}/{package_name}` instead of `app/...` and I'd recommend to stick with this version, but it require to create a new repository for every added module i.e. modified theme.

Working with M2 is a bit more complicated than M1, so I'd advice to read docs one more time or try to find some "how to basics", b/c I'm not able to support you with everything.

**Comment by gcampedelli** [comment]
Hello Igloczek. 

I was able to manage by myself a Magento install 2.1.3, composer install your modules, verify that everything is ok. Ir worked so far except for the fact that Yarn is much faster and better when we have to npm install in frontools module. So far so good. But when I gulp styles in frontools, I'm still getting error messages despite the fact everything is properly installed. So the error message I get is this one

Error in plugin 'run-sequence(inheritance)'
Message:
    ENOENT: no such file or directory, symlink '/var/www/html/magento2/vendor/snowdog/theme-blank-sass/Magento_AdvancedCheckout/styles/_module.scss' -> '/var/www/html/magento2/var/view_preprocessed/frontools/frontend/Snowdog/blank/Magento_AdvancedCheckout/styles/_module.scss'
Details:
    errno: -2
    code: ENOENT
    syscall: symlink
    path: /var/www/html/magento2/vendor/snowdog/theme-blank-sass/Magento_AdvancedCheckout/styles/_module.scss
    dest: /var/www/html/magento2/var/view_preprocessed/frontools/frontend/Snowdog/blank/Magento_AdvancedCheckout/styles/_module.scss
Stack:
Error: ENOENT: no such file or directory, symlink '/var/www/html/magento2/vendor/snowdog/theme-blank-sass/Magento_AdvancedCheckout/styles/_module.scss' -> '/var/www/html/magento2/var/view_preprocessed/frontools/frontend/Snowdog/blank/Magento_AdvancedCheckout/styles/_module.scss'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at createSymlink (/var/www/html/magento2/vendor/snowdog/frontools/helper/inheritance-resolver.js:16:18)
    at plugins.globby.sync.forEach.srcPath (/var/www/html/magento2/vendor/snowdog/frontools/helper/inheritance-resolver.js:41:7)
    at Array.forEach (native)
    at module.exports (/var/www/html/magento2/vendor/snowdog/frontools/helper/inheritance-resolver.js:40:8)
    at themes.forEach.name (/var/www/html/magento2/vendor/snowdog/frontools/task/inheritance.js:9:46)
    at Array.forEach (native)
    at Object.module.exports (/var/www/html/magento2/vendor/snowdog/frontools/task/inheritance.js:8:10)
    at module.exports (/var/www/html/magento2/vendor/snowdog/frontools/node_modules/orchestrator/lib/runTask.js:34:7)

Did I make something wrong? Is it themes.json? 

Anyway, thank you so much for your advice. I think others reading this can overcome their mistakes as well and soon I think we can close this thread as solved. But it looks like a nice work, but I still can't get blank-sass styles in place. I read you instructions, maybe there is something there I misunderstood. But for instance, reading your instructions I found out yarn is better than npm and so on. Maybe a final instruction can help everybody with same issue.

**Comment by Igloczek** [comment]
Kinda weird... Did you make any changes in `vendor/snowdog/theme-blank-sass`? You shouldn't.
If not, try to remove `var/view_preprocessed` and run `gulp styles` again.

**Comment by gcampedelli** [comment]
Wow, just worked! Nice work to go on! Congratulations on that! I will try to go further and deploy my on theme using yours as base. 
For instance, thanks a lot for your support.

**Comment by Igloczek** [comment]
You're welcome :)
