### ISSUE TITLE
Inheritance task errors

### ISSUE THREAD

**Issue by airdrumz** [SnowdogApps/magento2-frontools#172]
When running `gulp --gulpfile tools/gulpfile.js styles --theme xxxxx`, I get the following (edited to just the juicy bit):

```
[09:50:05] Starting 'inheritance'...
[09:50:05] 'inheritance' errored after 529 ms
[09:50:05] TypeError: Path must be a string. Received [ '/my/path/here/public_html/app/design/frontend/Xxx/xxxxx',
  '' ]
    at assertPath (path.js:7:11)
    at normalize (path.js:1177:5)
    at Array.map (native)
    at generateSymlinks (/my/path/here/public_html/vendor/snowdog/frontools/helper/inheritance-resolver.js:18:39)
    at theme.locale.forEach.locale (/my/path/here/public_html/vendor/snowdog/frontools/helper/inheritance-resolver.js:151:9)
    at Array.forEach (native)
    at themeDependencyTree.forEach.themeName (/my/path/here/public_html/vendor/snowdog/frontools/helper/inheritance-resolver.js:97:20)
    at Array.forEach (native)
    at module.exports (/my/path/here/public_html/vendor/snowdog/frontools/helper/inheritance-resolver.js:55:29)
    at themes.forEach.name (/my/path/here/public_html/vendor/snowdog/frontools/task/inheritance.js:9:46)
[09:50:05] TypeError in plugin 'run-sequence(inheritance)'
Message:
    Path must be a string. Received [ '/my/path/here/public_html/app/design/frontend/Xxx/xxxxx',
  '' ]
Stack:
TypeError: Path must be a string. Received [ '/my/path/here/public_html/app/design/frontend/Xxx/xxxxx',
  '' ]
    at assertPath (path.js:7:11)
    at normalize (path.js:1177:5)
    at Array.map (native)
    at generateSymlinks (/my/path/here/public_html/vendor/snowdog/frontools/helper/inheritance-resolver.js:18:39)
    at theme.locale.forEach.locale (/my/path/here/public_html/vendor/snowdog/frontools/helper/inheritance-resolver.js:151:9)
    at Array.forEach (native)
    at themeDependencyTree.forEach.themeName (/my/path/here/public_html/vendor/snowdog/frontools/helper/inheritance-resolver.js:97:20)
    at Array.forEach (native)
    at module.exports (/my/path/here/public_html/vendor/snowdog/frontools/helper/inheritance-resolver.js:55:29)
    at themes.forEach.name (/my/path/here/public_html/vendor/snowdog/frontools/task/inheritance.js:9:46)
[09:50:08] Theme: xxxxx Locale: en_GB main.css Compiled!
```

This is with version 1.3.8. If I downgrade to 1.3.7, all is well again.

**Comment by Igloczek** [comment]
Fix released as 1.3.9
