### ISSUE TITLE
syntax error on gulp deploy, see config/themes.json.sample

### ISSUE THREAD

**Issue by cmunshaw** [SnowdogApps/magento2-frontools#177]
undefined:32
    "ignore"" {
            ^

SyntaxError: Unexpected string in JSON at position 975
    at Object.parse (native)
    at module.exports (C:\shared\ICP\build\magento-2\vendor\snowdog\frontools\helper\config-loader.js:15:19)
    at Object.<anonymous> (C:\shared\ICP\build\magento-2\vendor\snowdog\frontools\gulpfile.js:20:50)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by Igloczek** [comment]
I made a typo in sample config, there should be `"ignore": {`.

**Comment by Igloczek** [comment]
Fixed in 1.4.3.
