### ISSUE TITLE
Not all assets getting copied into pub/static 

### ISSUE THREAD

**Issue by crantron** [SnowdogApps/magento2-frontools#19]
go here: http://chef4.dev3.gigasavvy.net/shop/restaurant-equipment and look in the error console. In developer mode it works find with php preprocessing not with this though. am I doing something wrong?

steps 
  - gulp clean
  - gulp deploy --theme chefstoys
  - gulp styles --theme chefstoys

**Comment by crantron** [comment]
also when i use : 
  - gulp release 

i get this error: 

```
Magento\Framework\Exception\FileSystemException]                     
  The "/home/chef4/public_html/shop/" file doesn't exist or not a file  
                                                                        


dev:source-theme:deploy [--type="..."] [--locale="..."] [--area="..."] [--theme="..."] [file1] ... [fileN]


[14:37:14] 'deploy' errored after 1.9 s
[14:37:14] Error: Command failed: ../bin/magento dev:source-theme:deploy --type=less --locale=en_US --area=adminhtml --theme=Magento/backend css/styles-old css/styles


                                                                        
  [Magento\Framework\Exception\FileSystemException]                     
  The "/home/chef4/public_html/shop/" file doesn't exist or not a file  
                                                                        


dev:source-theme:deploy [--type="..."] [--locale="..."] [--area="..."] [--theme="..."] [file1] ... [fileN]



    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at /home/chef4/public_html/shop/tools/tasks/deploy.js:32:13
    at Array.forEach (native)
    at /home/chef4/public_html/shop/tools/tasks/deploy.js:27:24
    at Array.forEach (native)
    at /home/chef4/public_html/shop/tools/tasks/deploy.js:24:35
    at Array.forEach (native)
    at Object.module.exports.themes.forEach.name (/home/chef4/public_html/shop/tools/tasks/deploy.js:23:12)
    at module.exports (/home/chef4/public_html/shop/tools/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
[14:37:14] Error in plugin 'run-sequence'
Message:
    An error occured in task 'deploy'.

```

**Comment by Igloczek** [comment]
It's Magento problem, not Frontools. As you see `deploy` task just run Magento CLI with your theme params.

Frontools compiles styles - thats's it. If you want another assets, use Magento CLI.
If you are not familiar with CLI or whole M2 it's to complicated - blame Magento engineers or some else 😉 

I'm working with M2 ~3 months and it's still mind blowing. You have to read about it little bit more and try to solve problems independently.
I can't spend hours answering questions not related to this project, really have better things to do than being "M2 helpdesk" 😄
