### ISSUE TITLE
gulpfile.js throwing Syntax Error Line 44

### ISSUE THREAD

**Issue by CNSam** [SnowdogApps/magento2-frontools#21]
Hello there,

Have just tried to run gulp dev and getting the following error:
```
/magento2ce/tools/gulpfile.js:44
Object.keys(configs.themes).forEach(name => {
                                          ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
```

I have generated the config file, PHPSTORM is also picking up on that section as:
Expression statement is not assignment or call

**Comment by Igloczek** [comment]
Looks like outdated node.js, b/c can't parse ES6 code. You should have current LTS `>= 4.0.0'

**Comment by CNSam** [comment]
Thanks @Igloczek - apologies, I thought my vagrant box was already up to date.

**Comment by Igloczek** [comment]
You're welcome 😉
