### ISSUE TITLE
inheritance syntax error

### ISSUE THREAD

**Issue by VincentMarmiesse** [SnowdogApps/magento2-frontools#216]
Hello,

When I try to launch `gulp deploy`, I have the following error:
```
[02:47:11] Using gulpfile /media/psf/Home/www/magento2/vendor/snowdog/frontools/gulpfile.js
[02:47:11] Starting 'deploy'...
[02:47:11] Starting 'inheritance'...
[02:47:11] 'inheritance' errored after 8.54 ms
[02:47:11] SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /media/psf/Home/www/magento2/vendor/snowdog/frontools/task/inheritance.js:9:5
    at Array.forEach (native)
    at Object.module.exports (/media/psf/Home/www/magento2/vendor/snowdog/frontools/task/inheritance.js:8:10)
[02:47:11] Finished 'deploy' after 21 ms
```

The error is caused by this part of the code in `vendor/snowdog/frontools/task/inheritance.js`:

```
themes.forEach(name => {
    require('../helper/inheritance-resolver')(plugins, config, name);
  });
```

It seems this `forEach` syntax isn't supported on my environment?

Thank you!

**Comment by VincentMarmiesse** [comment]
Ok my bad, upgrading `node` and `npm` solved my issue.
