### ISSUE TITLE
Problem with run-sequence(styles) Magento 2.3

### ISSUE THREAD

**Issue by Krystian-Nikiel** [SnowdogApps/magento2-frontools#331]
Hey i have a problem with plugin: run-sequence( style )
Commend "gulp styles" in Magento 2.3 give me error: 

```
Error in plugin "run-sequence(styles)"
Error
    at finish (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/run-sequence/index.js:82:12)
    at Gulp.onError (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/run-sequence/index.js:93:3)
    at emitOne (events.js:121:20)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/index.js:264:8)
    at /Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/index.js:275:23
    at finish (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/index.js:214:10)
```
How I can fix this problem? :(

**Comment by Krystian-Nikiel** [comment]
`iMac-Ageno:tools agenopl$ gulp styles --ci
[13:25:26] Using gulpfile ~/Sites/kulig-b2b/vendor/snowdog/frontools/gulpfile.js
[13:25:26] Starting 'styles'...
[13:25:26] Starting 'inheritance'...
[13:25:30] 'styles' errored after 3.26 s
[13:25:30] Error in plugin 'config'
Message:

====================================
You have to create browserslist.json
====================================
[13:25:30] Error in plugin "run-sequence(styles)"
Error
    at finish (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/run-sequence/index.js:82:12)
    at Gulp.onError (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/run-sequence/index.js:93:3)
    at emitOne (events.js:121:20)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/index.js:264:8)
    at /Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/index.js:275:23
    at finish (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/agenopl/Sites/kulig-b2b/vendor/snowdog/frontools/node_modules/orchestrator/index.js:214:10)
[13:25:30] Finished 'inheritance' after 3.3 s`

browserslist.json is required?

**Comment by Igloczek** [comment]
Yes, it is as the error clearly says.
If you want to use the default one, just run `gulp setup` and everything will work just fine.
