### ISSUE TITLE
styles task error

### ISSUE THREAD

**Issue by iskanderokilov** [SnowdogApps/magento2-frontools#371]
hi, after the latest updates styles task and also for example dev task starts with a error:
```
[09:54:48] 'styles' errored after 5.37 ms
[09:54:48] ReferenceError: plugins is not defined
    at eval (eval at <anonymous> (/var/www/magento2/vendor/snowdog/frontools/helpers/scss.js:33:34), <anonymous>:1:1)
    at /var/www/magento2/vendor/snowdog/frontools/helpers/scss.js:33:34
    at Array.forEach (<anonymous>)
    at default (/var/www/magento2/vendor/snowdog/frontools/helpers/scss.js:32:19)
    at /var/www/magento2/vendor/snowdog/frontools/tasks/styles.js:8:17
    at Array.forEach (<anonymous>)
    at styles (/var/www/magento2/vendor/snowdog/frontools/tasks/styles.js:7:12)
    at bound (domain.js:419:14)
    at runBound (domain.js:432:12)
    at asyncRunner (/var/www/magento2/vendor/snowdog/frontools/node_modules/async-done/index.js:55:18)
[09:54:48] 'styles' errored after 480 ms
```
before work all beautiful...

**Comment by Igloczek** [comment]
It's a change introduced in 1.8.0, you need to update your config.
https://github.com/SnowdogApps/magento2-frontools/releases/tag/1.8.0
