### ISSUE TITLE
Can't deploy or compile less theme

### ISSUE THREAD

**Issue by Bartlomiejsz** [SnowdogApps/magento2-frontools#76]
When I try to use command:
`gulp deploy --theme=blank' it gives me following error:

![2016-08-23_07h38_52](https://cloud.githubusercontent.com/assets/9566840/17881354/00f4b842-6905-11e6-8f9e-0029e4684805.png)

Do you know why so?

**Comment by Igloczek** [comment]
Your gulp process is launched by different user, without permissions to run `bin/magento`

BTW. Please copy past console output here inside  \`\`\` tags, instead of screen shooting your console.

**Comment by BenSpace48** [comment]
I am getting this error even when running as root (su). Running on a Mac (OSX 10.10.2). The problem is the permissions of the `bin/magento` command.

```
[root@project-name-m2-local tools]# gulp deploy
[15:58:38] Using gulpfile /var/www/vhosts/project-name/production/htdocs/vendor/snowdog/frontools/gulpfile.js
[15:58:38] Starting 'deploy'...
/bin/sh: /var/www/vhosts/project-name/production/htdocs/bin/magento: Permission denied
[15:58:38] 'deploy' errored after 9.01 ms
[15:58:38] Error: Command failed: /var/www/vhosts/project-name/production/htdocs/bin/magento dev:source-theme:deploy --type=less --locale=en_GB --area=adminhtml --theme=Magento/backend css/styles-old css/styles
/bin/sh: /var/www/vhosts/project-name/production/htdocs/bin/magento: Permission denied

    at checkExecSyncError (child_process.js:465:13)
    at execSync (child_process.js:505:13)
    at /var/www/vhosts/project-name/production/htdocs/vendor/snowdog/frontools/task/deploy.js:19:9
    at Array.forEach (native)
    at /var/www/vhosts/project-name/production/htdocs/vendor/snowdog/frontools/task/deploy.js:14:20
    at Array.forEach (native)
    at Object.module.exports.themes.forEach.theme.locale.forEach.theme.locale.forEach (/var/www/vhosts/project-name/production/htdocs/vendor/snowdog/frontools/task/deploy.js:10:10)
    at module.exports (/var/www/vhosts/project-name/production/htdocs/vendor/snowdog/frontools/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/vhosts/project-name/production/htdocs/vendor/snowdog/frontools/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/vhosts/project-name/production/htdocs/vendor/snowdog/frontools/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
```

The problem was the bin/magento command wasn't executable, I suspect other people will have this problem not every has changed the permissions for it. 

As a workaround I changed the following by doing the below:

1. Navigate to the `bin` directory
2. Run `chmod -x magento` - This sets the magento cli to be executable without adding php beforehand.

I suppose it's up to you @Igloczek whether something is added so `php` can be toggled on or off when running `bin/magento` through gulp or possibly add some info to the error letting the user know the permissions of `bin/magento` need to be changed.

CC @Bartlomiejsz in case you didn't get it resolved.

**Comment by Igloczek** [comment]
Support for LESS themes will be dropped in next version, so I'm not going to change anything in this topic, b/c for SASS themes using `bin/magento` isn't necessary.

Also error message is clear to understand. User running Gulp needs same permissions as user running CLI and there is no way to handle permissions on Gulp task level.
