### ISSUE TITLE
Deploy error on Windows

### ISSUE THREAD

**Issue by Aldecoez** [SnowdogApps/magento2-frontools#80]
```
[15:08:38] Using gulpfile C:\xampp\htdocs\magento_2\vendor\snowdog\frontools\gulpfile.js
[15:08:38] Starting 'deploy'...
'C:\xampp\htdocs\magento_2/bin/magento' is not recognized as an internal or external command,
operable program or batch file.
[15:08:38] 'deploy' errored after 7.85 ms
[15:08:38] Error: Command failed: C:\xampp\htdocs\magento_2/bin/magento dev:source-theme:deploy --type=less --locale=en_US --area=adminhtml --theme=Magento/backend css/styles-old css/styles
'C:\xampp\htdocs\magento_2/bin/magento' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at C:\xampp\htdocs\magento_2\vendor\snowdog\frontools\task\deploy.js:19:9
    at Array.forEach (native)
    at C:\xampp\htdocs\magento_2\vendor\snowdog\frontools\task\deploy.js:14:20
    at Array.forEach (native)
    at Object.module.exports.themes.forEach.theme.locale.forEach.theme.locale.forEach (C:\xampp\htdocs\magento_2\vendor\snowdog\frontools\task\deploy.js:10:10)
    at module.exports (C:\xampp\htdocs\magento_2\vendor\snowdog\frontools\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\xampp\htdocs\magento_2\vendor\snowdog\frontools\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\xampp\htdocs\magento_2\vendor\snowdog\frontools\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
```
I guess that problem is in Windows with that slashes. Or some other idea?

**Comment by Igloczek** [comment]
I didn't test it on Windows and now I'm on vacation, so let's try to fix it independently.
Let's change slashes in `task/deploy.js` file and test it  😉

**Comment by Aldecoez** [comment]
I tried and problem is somewhere else. I would be grateful if you could fix it after the holidays

**Comment by Igloczek** [comment]
Could you send me error log after changing `/` to `\`, maybe I will not have to setup everything on Windows and my hands will stay clean 😜
#advice -let's use some virtualization to keep codebase on unix like OS, it's always easier to maintain.

**Comment by Igloczek** [comment]
Let's check if user runing gulp command have executions rights on `bin/magento` file.
Also, let's try to execute `C:/xampp/htdocs/magento_2/bin/magento dev:source-theme:deploy --type=less --locale=en_US --area=adminhtml --theme=Magento/backend css/styles-old css/styles` manualy, maybe we just can't use absolute paths on Windows...

**Comment by Aldecoez** [comment]
I ran with admin rights so rights ain't a problem.
Manually launched work, there is succesfull message :open_mouth:

**Comment by Igloczek** [comment]
So I'm currently out of ideas 😞  Will try to debug this on next week.

**Comment by Resedano** [comment]
Hi. There is still this error on my console. I have to run this command mannualy before using your tool. Is there a walkaround to avoid this bug? I'm not a Command-line interface expert. Sorry. Thank you.
Mauro

**Comment by Igloczek** [comment]
I'm preparing now v1.0.0 without LESS support, so I'm not going to invest time in debugging this, it looks like a weird way of spawning child process on Windows.
If you find out a way, how to fix it, let's send it, will make manually a hotfix for older version.
