### ISSUE TITLE
module not starting

### ISSUE THREAD

**Issue by to8gal** [SnowdogApps/magento2-frontools#92]
Hello,

I kin of understand this is me somewhere but dunno where, node is 4.* and all rest should be there,

when I go to frontools directory and launche setup with gulp setup trow this:

module.js:427
    throw err;
    ^

SyntaxError: /Users/.../vendor/snowdog/frontools/config/themes.json: Unexpected string
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:424:27)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/Users/.../vendor/snowdog/frontools/helper/config-loader.js:23:14)
    at Object.<anonymous> (/Users/.../vendor/snowdog/frontools/gulpfile.js:21:50)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

where am I wrong?

**Comment by Igloczek** [comment]
Your `themes.json` isn't a proper JSON file. Check if all `"` and `,` are placed in right place.

**Comment by to8gal** [comment]
I see, that was really stupid of me, a mssing comma

**Comment by to8gal** [comment]
I guess we can clse this one
